### ISSUE TITLE
`UnityExtensions.LocateFSM(this GameObject, string)`  is the same as `FSMUtility.LocateMyFSM(this GameObject, string)`

### ISSUE THREAD

**Issue by SFGrenade** [homothetyhk/HollowKnight.ItemChanger#8]
https://github.com/homothetyhk/HollowKnight.ItemChanger/blob/995fef3fecc3c3f85e4c67a2785becffe98524d3/ItemChanger/Extensions/UnityExtensions.cs#L8-L11

**Comment by homothetyhk** [comment]
I believe it is a style choice carried over from the previous SereCore dependency. I'll consider removing it in the next update, but it isn't a high priority.

**Comment by homothetyhk** [comment]
Fixed by 1d8c2908536243b17708a596862fb16d4127d866.
